@URL = http://localhost:3000
@token = 

### 1. Listar todos los usuarios (Privado - Solo Admin)
GET {{URL}}/usuarios
Authorization: Bearer {{token}}

### 2. Obtener un usuario por ID (Privado - Solo Admin)
GET {{URL}}/usuarios/1
Authorization: Bearer {{token}}

